#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*|*MINGW*|*MSYS*) basedir=`cygpath -w "$basedir"`;;
esac

exec "C:/Users/asti/AppData/Roaming/xPacks/@xpack-dev-tools/openocd/0.11.0-5.1/.content/bin/openocd.exe"   "$@"
